apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreder-service-app
spec:
  selector:
    matchLabels:
      app: oreder-service-app
  template:
    metadata:
      labels:
        app: oreder-service-app
    spec:
      containers:
      - name: oreder-service-app
        image: shoaibpki/orderservice
        ports:
        - containerPort: 8082
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          # - name: EUREKA_SERVER_ADDRESS
          #   valueFrom:
          #     configMapKeyRef:
          #       key: eureka_service_address
          #       name: eureka-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: oreder-service-app
  ports:
  - port: 80
    targetPort: 8082

