server:
  port: 9296
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shoaibpki/spring-app-config.git
          clone-on-start: true
          default-label: main
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#okta:
#  oauth2:
#    issuer: https://dev-26589103.okta.com/oauth2/default
#    audience: api://default